import { Router, type IRouter } from "express";
import healthRouter from "./health";
import researchRouter from "./research";
import scriptsRouter from "./scripts";
import storyboardsRouter from "./storyboards";
import assetsRouter from "./assets";
import projectsRouter from "./projects";
import pipelinesRouter from "./pipelines";
import jobsRouter from "./jobs";
import analyticsRouter from "./analytics";
import logsRouter from "./logs";
import settingsRouter from "./settings";
import timelinesRouter from "./timelines";
import voicesRouter from "./voices";
import renderRouter from "./render";
import subtitlesRouter from "./subtitles";
import thumbnailsRouter from "./thumbnails";
import chaptersRouter from "./chapters";
import productionAssetsRouter from "./production-assets";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/research", researchRouter);
router.use("/scripts", scriptsRouter);
router.use("/storyboards", storyboardsRouter);
router.use("/assets", assetsRouter);
router.use("/timelines", timelinesRouter);
router.use("/voices", voicesRouter);
router.use("/renders", renderRouter);
router.use("/subtitles", subtitlesRouter);
router.use("/thumbnails", thumbnailsRouter);
router.use("/chapters", chaptersRouter);
router.use("/production-assets", productionAssetsRouter);
router.use("/projects", projectsRouter);
router.use("/pipelines", pipelinesRouter);
router.use("/jobs", jobsRouter);
router.use("/analytics", analyticsRouter);
router.use("/logs", logsRouter);
router.use("/settings", settingsRouter);

export default router;
